wallpaper {
    monitor = eDP-1
#    path = ~/Pictures/Wallpapers/wp11158332.jpg
#    path = ~/DCIM/Camera/IMG_20251203_094303.jpg
    path = ~/Pictures/Wallpapers/951.png
#    path = ~/Pictures/Wallpapers/wp11158332.jpg
#    path = ~/Pictures/Wallpapers/quake2.png

    fit_mode = cover
}

splash = false

