[skin]
description = DOS Navigator's VAX Vibrant

[Lines]
horiz = ─
vert = │
lefttop = ┌
righttop = ┐
leftbottom = └
rightbottom = ┘
topmiddle = ┬
bottommiddle = ┴
leftmiddle = ├
rightmiddle = ┤
cross = ┼
dhoriz = ═
dvert = ║
dlefttop = ╔
drighttop = ╗
dleftbottom = ╚
drightbottom = ╝
dtopmiddle = ╤
dbottommiddle = ╧
dleftmiddle = ╟
drightmiddle = ╢
#dhoriz = ─
#dvert = │
#dlefttop = ┌
#drighttop = ┐
#dleftbottom = └
#drightbottom = ┘
#dtopmiddle = ┬
#dbottommiddle = ┴
#dleftmiddle = ├
#drightmiddle = ┤

[core]
_default_ = brightgreen;black
selected = black;lightgray
marked = brightyellow;
markselect = brightyellow;lightgray
gauge = ;yellow
input = brightgreen;
disabled = gray;
reverse = brightgreen;
header = lightgray;
inputhistory =
commandhistory =
shadow = gray;black

[dialog]
_default_ = brightgreen;black
dfocus = brightyellow;black
dhotnormal = brightred;
dhotfocus = brightyellow;black
dtitle = brightgreen;

[error]
_default_ = white;
errdfocus = brightgreen;
errdhotnormal = brightyellow;
errdhotfocus = brightyellow;
errdtitle = brightyellow;

[filehighlight]
directory = lightgray;
executable = brightgreen;
symlink = brightred;
hardlink =
stalelink = brightred;
device = brightgreen;
special = brightblue;
core = brightred;
temp = gray;
archive = brightcyan;
doc = yellow;
source = brightgreen;
media = white;
graph = brightmagenta;
database = ;

[menu]
_default_ = brightgreen;black
menusel = black;brightgreen
menuhot = brightyellow;
menuhotsel = brightyellow;
menuinactive = brightgreen;

[popupmenu]
_default_ = brightgreen;black
menusel = brightgreen;black
menutitle = brightgreen;black

[buttonbar]
hotkey = brightgreen;black
button = brightgreen;black

[statusbar]
_default_ = brightgreen;black

[help]
_default_ = brightgreen;black
helpitalic = brightcyan;
helpbold = brightgreen;
helplink = white;
helpslink = brightyellow;
helptitle = brightgreen;

[editor]
_default_ = lightgray;black
editbold = brightyellow;brightblue
editmarked = brightgreen;red
editwhitespace = brightblue;brightblue
editnonprintable = ;black
editlinestate = brightgreen
bookmark = white;red
bookmarkfound = black;brightgreen
editrightmargin = brightblue;brightblue
editframeactive = white;
editframedrag = brightgreen;

[viewer]
_default_ = brightgreen;black
viewbold = brightred;black
viewunderline = brightgreen;black
viewselected = brightyellow;black

[diffviewer]
_default_ = lightgray;black
added = brightgreen;
changedline = brightcyan;
changednew = brightyellow;
changed = ;yellow
removed = ;brightblue
error = white;red

[widget-panel]
filename-scroll-left-char = {
filename-scroll-right-char = }

[widget-editor]
window-state-char = *
window-close-char = X
