[skin]
description = DOS Navigator's VAX
truecolors = true

[Lines]
horiz = ─
vert = │
lefttop = ┌
righttop = ┐
leftbottom = └
rightbottom = ┘
topmiddle = ┬
bottommiddle = ┴
leftmiddle = ├
rightmiddle = ┤
cross = ┼
dhoriz = ═
dvert = ║
dlefttop = ╔
drighttop = ╗
dleftbottom = ╚
drightbottom = ╝
dtopmiddle = ╤
dbottommiddle = ╧
dleftmiddle = ╟
drightmiddle = ╢
#dhoriz = ─
#dvert = │
#dlefttop = ┌
#drighttop = ┐
#dleftbottom = └
#drightbottom = ┘
#dtopmiddle = ┬
#dbottommiddle = ┴
#dleftmiddle = ├
#drightmiddle = ┤

[core]
_default_ = green;black
selected = black;lightgray
marked = #ffff00;#000000;bold
markselect = #000000;#ffff00;bold
gauge = ;brown
input = brightgreen;black
disabled = gray;black
reverse = black;lightgray
header = lightgray;
inputhistory = brightgreen;black
commandhistory = brightgreen;black
shadow = gray;black

[dialog]
_default_ = brightgreen;black
dfocus = black;lightgray
dhotnormal = brightyellow;black
dhotfocus = black;lightgray
dtitle = lightgray;black

[error]
_default_ = #cccccc;#000000
errdfocus = #000000;#c0c0c0
errdhotnormal = #ffff00;#000000;bold
errdhotfocus = #000000;#c0c0c0;bold
errdtitle = #ffff00;#000000;bold

[filehighlight]
directory = lightgray;
executable = brightgreen;
symlink = brightcyan;
hardlink = cyan;
stalelink = brightred;
device = yellow;
special = brightblue;
core = brightred;
temp = gray;black
archive = brightcyan;
doc = yellow;
source = brightgreen;
media = white;
graph = magenta;
database = cyan;

[menu]
_default_ = green;black
menusel = black;lightgray
menuhot = brightyellow;black
menuhotsel = black;lightgray
menuinactive = gray;black

[popupmenu]
_default_ = green;black
menusel = black;lightgray
menutitle = lightgray;black

[buttonbar]
hotkey = brightgreen;black
button = green;black

[statusbar]
_default_ = green;black

[help]
_default_ = brightgreen;black
helpitalic = brightcyan;
helpbold = brightgreen;
helplink = white;
helpslink = black;lightgray
helptitle = lightgray;black

[editor]
_default_ = lightgray;black
editbold = yellow;blue
editmarked = black;lightgray
editwhitespace = brightblue;blue
editnonprintable = ;black
editlinestate = brightgreen
bookmark = white;red
bookmarkfound = black;lightgray
editrightmargin = brightblue;blue
#    editbg =
#    editframe =
editframeactive = white;
editframedrag = green;

[viewer]
_default_ = green;black
viewbold = brightred;black
viewunderline = brightgreen;black
viewselected = black;lightgray

[diffviewer]
_default_ = lightgray;black
added = brightgreen;
changedline = brightcyan;
changednew = black;lightgray
changed = ;brown
removed = brightred;black
error = white;red

[widget-panel]
filename-scroll-left-char = {
filename-scroll-right-char = }

[widget-editor]
window-state-char = *
window-close-char = X
