[skin]
description = DOS Navigator's VAX

[Lines]
horiz = ─
vert = │
lefttop = ┌
righttop = ┐
leftbottom = └
rightbottom = ┘
topmiddle = ┬
bottommiddle = ┴
leftmiddle = ├
rightmiddle = ┤
cross = ┼
dhoriz = ═
dvert = ║
dlefttop = ╔
drighttop = ╗
dleftbottom = ╚
drightbottom = ╝
dtopmiddle = ╤
dbottommiddle = ╧
dleftmiddle = ╟
drightmiddle = ╢
#dhoriz = ─
#dvert = │
#dlefttop = ┌
#drighttop = ┐
#dleftbottom = └
#drightbottom = ┘
#dtopmiddle = ┬
#dbottommiddle = ┴
#dleftmiddle = ├
#drightmiddle = ┤

[core]
_default_ = green;black
selected = black;lightgray
marked = yellow;
markselect = yellow;lightgray
gauge = ;brown
input = brightgreen;
disabled = gray;
reverse = brightgreen;
header = lightgray;
inputhistory =
commandhistory =
shadow = gray;black

[dialog]
_default_ = brightgreen;black
dfocus = yellow;black
dhotnormal = brightred;
dhotfocus = yellow;black
dtitle = brightgreen;

[error]
_default_ = white;
errdfocus = brightgreen;
errdhotnormal = yellow;
errdhotfocus = yellow;
errdtitle = yellow;

[filehighlight]
directory = lightgray;
executable = brightgreen;
symlink = red;
hardlink =
stalelink = red;
device = green;
special = brightblue;
core = red;
temp = gray;
archive = cyan;
doc = brown;
source = green;
media = white;
graph = magenta;
database = ;

[menu]
_default_ = green;black
menusel = black;green
menuhot = yellow;
menuhotsel = yellow;
menuinactive = green;

[popupmenu]
_default_ = green;black
menusel = brightgreen;black
menutitle = brightgreen;black

[buttonbar]
hotkey = brightgreen;black
button = green;black

[statusbar]
_default_ = green;black

[help]
_default_ = brightgreen;black
helpitalic = brightcyan;
helpbold = brightgreen;
helplink = white;
helpslink = yellow;
helptitle = brightgreen;

[editor]
_default_ = lightgray;black
editbold = yellow;blue
editmarked = brightgreen;red
editwhitespace = brightblue;blue
editnonprintable = ;black
editlinestate = brightgreen
bookmark = white;red
bookmarkfound = black;green
editrightmargin = brightblue;blue
#    editbg =
#    editframe =
editframeactive = white;
editframedrag = green;

[viewer]
_default_ = green;black
viewbold = brightred;black
viewunderline = brightgreen;black
viewselected = yellow;black

[diffviewer]
_default_ = lightgray;black
added = brightgreen;
changedline = cyan;
changednew = yellow;
changed = ;brown
removed = ;blue
error = white;red

[widget-panel]
filename-scroll-left-char = {
filename-scroll-right-char = }

[widget-editor]
window-state-char = *
window-close-char = X

