Net/ThemeName "VAX"
Net/IconThemeName "Chicago95"
Gtk/ColorScheme "fg_color:#000000\nbg_color:#c0c0c0\nbase_color:#ffffff\ntext_color:#000000\nselected_bg_color:#001a00\nselected_fg_color:#00ff41"
Gtk/FontName "Microsoft Sans Serif 8"
Gtk/CursorThemeName "Chicago95 Standard Cursors"
Gtk/ToolbarStyle 3
Gtk/ButtonImages 1
Gtk/MenuImages 1
