focus-exclude = "x = 0 && y = 0 && override_redirect = true";
// "class_g = 'firefox' && argb",

rules: ({
    match = "window_type = 'normal'";
    shader = "/home/user/.local/src/picom-shaders/Animations/pixelize.glsl";
})
animations = ({
    opacity-duration = 0.5;
    triggers = ["open", "show"];
    opacity-curve = {
        curve = "cubic-bezier(0.5, 0.5, 0.5, 0.5)";
        start = 0;
        end = 1;
        duration = "opacity-duration";
        }
    opacity = "opacity-curve";
    }, {
    opacity-duration = 0.2;
    triggers = ["close", "hide"];
    opacity-curve = {
        curve = "cubic-bezier(0.5, 0.5, 0.5, 0.5)";
        start = 1;
        end = 0;
        duration = "opacity-duration";
        }
    opacity = "opacity-curve";
    }
)

