wallpaper {
    monitor = eDP-1
#    path = /home/user/Data/Documents/Pictures/Wallpapers/wp11158332.jpg
#    path = /home/user/Data/Documents/DCIM/Camera/IMG_20251203_094303.jpg
#    path = ~/Data/Documents/Pictures/Wallpapers/951.png
    path = ~/Data/Documents/Pictures/Wallpapers/wp11158332.jpg

    fit_mode = cover
}

splash = false

