$mono = FiraCode Nerd Font

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    blur_passes = 0
    color = rgba(000000ff)
}

shape {
    monitor =
    size = 420, 190
    color = rgba(c0c0c0ff)
    border_size = 2
    border_color = rgba(ffffffff)
    rounding = 0
    position = 0, 0
    halign = center
    valign = center
}

shape {
    monitor =
    size = 416, 186
    color = rgba(c0c0c000)
    border_size = 2
    border_color = rgba(000000ff)
    rounding = 0
    position = 2, -2
    halign = center
    valign = center
}

shape {
    monitor =
    size = 398, 24
    color = rgba(003300ff)
    border_size = 0
    rounding = 0
    position = 0, 74
    halign = center
    valign = center
}

shape {
    monitor =
    size = 312, 46
    color = rgba(000000ff)
    border_size = 2
    border_color = rgba(808080ff)
    rounding = 0
    position = 42, -34
    halign = center
    valign = center
}

label {
    monitor =
    text = Login
    font_size = 14
    font_family = $mono
    color = rgba(00ff41ff)

    position = -160, 74
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_size = 72
    font_family = $mono
    color = rgba(00ff41ff)

    position = 0, 170
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 20
    font_family = $mono
    color = rgba(00ff41ff)

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = Password:
    font_size = 14
    font_family = $mono
    color = rgba(000000ff)

    position = -155, -34
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 38
    outline_thickness = 0
    dots_size = 0.35
    dots_spacing = 0.35
    dots_center = true
    inner_color = rgba(001100ff)
    outer_color = rgba(00000000)
    check_color = rgba(00ff41ff)
    fail_color = rgba(ff4444ff)
    font_color = rgba(00ff41ff)
    font_family = $mono
    fade_on_empty = false
    rounding = 0
    placeholder_text = Enter password...
    fail_text = <b>$FAIL</b>
    hide_input = false
    position = 42, -34
    halign = center
    valign = center
}

label {
    monitor =
    text = Press Enter to unlock
    font_size = 12
    font_family = $mono
    color = rgba(202020ff)

    position = 0, -76
    halign = center
    valign = center
}

label {
    monitor =
    text = Press <b>ESC</b> to clear  |  <b>Ctrl+U</b> to reset
    font_size = 12
    font_family = $mono
    color = rgba(808080ff)

    position = 0, 50
    halign = center
    valign = bottom
}
