[*]
wallpaper_mode=color
wallpaper_common=1
desktop_bg=#008080
desktop_fg=#ffffff
desktop_shadow=#000000
desktop_font=Microsoft Sans Serif 8
show_wm_menu=0
sort=name;ascending;
show_documents=0
show_trash=1
show_mounts=1

[xfce4-web-browser.desktop]
x=2
y=1339

[xfce4-taskmanager.desktop]
x=7
y=228

[q2manager.desktop]
x=2
y=919

[kitty.desktop]
x=3
y=1210

