[*]
wallpaper_mode=color
wallpaper_common=1
wallpaper=/home/user/Downloads/8bcd64dc-ede9-4714-90c4-bb0e065e96fe.png
desktop_bg=#008080
desktop_fg=#ffffff
desktop_shadow=#000000
desktop_font=Microsoft Sans Serif 8
show_wm_menu=0
sort=name;ascending;
show_documents=0
show_trash=1
show_mounts=1

[xfce4-web-browser.desktop]
x=2
y=1032

[xfce4-taskmanager.desktop]
x=7
y=228

[q2manager.desktop]
x=2
y=818

[kitty.desktop]
x=2
y=925

