#!/usr/bin/env bash
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

xrdb -load "$XDG_CONFIG_HOME/X11/xresources"

xset s off
xset -dpms

#picom --no-use-damage --backend glx --config ~/.config/picom.conf &
#xsetroot -solid '#008080' # incompatible with picom
hsetroot -solid '#008080'
# feh --bg-scale ~/Pictures/Wallpapers/951.png &
syncthing --no-browser 2>&1 >/dev/null &
fluidsynth -a pulseaudio /usr/share/soundfonts/FluidR3_GM.sf2 -q -s &
setxkbmap pl

~/Projects/scripts/dwm-status.sh &
exec dbus-run-session dwm

#sxbar &
#exec sxwm

