#!/usr/bin/env bash
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

xrdb -load "$XDG_CONFIG_HOME/X11/xresources"

#picom --no-use-damage --backend glx --config ~/.config/picom.conf &
#xsetroot -solid '#008080' # incompatible with picom
hsetroot -solid '#008080'
# feh --bg-scale ~/Pictures/Wallpapers/951.png &

# Should be started after login in framebuffer
syncthing --no-browser 2>&1 >/dev/null &
#fluidsynth -a pulseaudio /usr/share/soundfonts/FluidR3_GM.sf2 -q -s &
mpd &
cd Documents/notes/html
python3 -m http.server 2>&1 >/dev/null &
cd -

setxkbmap pl &

#~/Projects/scripts/dwm-status.sh &
#exec dbus-run-session dwm

#exec dbus-run-session startxfce4

#sxbar &
#exec sxwm

#exec fluxbox
#snixembed &

#exec openbox-session
exec dbus-run-session openbox-session
