#!/usr/bin/env bash
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

xrdb -load "$XDG_CONFIG_HOME/X11/xresources"

xset s off
xset -dpms
setxkbmap pl

picom --no-use-damage --backend glx --config ~/.config/picom.conf &
#xsetroot -solid '#008080' # incompatible with picom
hsetroot -solid '#008080'
# feh --bg-scale ~/Pictures/Wallpapers/951.png &
syncthing --no-browser &
fluidsynth -a pulseaudio /usr/share/soundfonts/FluidR3_GM.sf2 -q -s &

~/Projects/scripts/dwm-status.sh &
#exec dbus-launch --sh-syntax --exit-with-session dwm

exec dwm

#sxbar &
#exec sxwm

